name: vartaa
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Pastikan versi SDK Anda kompatibel.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  # go_router: # (aktifkan jika dipakai)
  # flutter_screenutil: # (aktifkan jika dipakai)
  # flutter_native_splash: # (aktifkan jika dipakai)

  phosphor_flutter: ^2.1.0
  carousel_slider: ^4.2.1
  http: ^1.2.1
  provider: ^6.0.5
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.1
  shared_preferences: ^2.2.3

  # --- Tambahkan kembali package yang terhapus di sini ---
  animated_splash_screen: ^1.3.0 # Tambahkan ini
  smooth_page_indicator: ^1.2.1 # Tambahkan ini
  # -----------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo_light.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/images/logo_dark.png'

flutter:
  uses-material-design: true

  assets:
    - images/
